linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive

issues:
  exclude-use-default: false
  exclude:
    - "should have a package comment"
  exclude-dirs:
    - vendor
    - third_party
